name: Feature Request
description: Suggest a new feature or improvement for the project
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature!

        Before continuing, please make sure to check if the feature has already been requested by searching through the existing issues.

  - type: textarea
    id: description
    attributes:
      label: Feature Overview
      description: A clear and concise overview of the feature.
      placeholder: I would like to be able to do X.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you have considered.
      placeholder: I have considered doing Y, but it doesn't provide the desired outcome.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information may be relevant to the feature request.
      placeholder: Feel free to add any other relevant information/screenshots that may be relevant to the feature request.
